server.port=8080
spring.application.name=cartel-admin-console
server.error.include-message=always

spring.profiles.active=prod


#---
spring.config.activate.on-profile=local

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.database=cartel-user-database


#---
spring.config.activate.on-profile=prod

spring.data.mongodb.uri=mongodb+srv://jimbo_db_user:${MONGODB_PASSWORD}@cartel-cluster.rhnc2gc.mongodb.net/cartel-user-database?appName=cartel-cluster